### ISSUE TITLE
Swift implementation 

### ISSUE THREAD

**Issue by chinnasamymca** [dleehr/DLSFTPClient#22]
Hi There, 

    How can we implement below functions in swift ? 

DLSFTPClientArraySuccessBlock successBlock = ^(NSArray *files) {
    for (DLSFTPFile *sftpFile in files) {
        NSLog(@"File: %@", sftpFile.filename);
    }
};

DLSFTPClientFailureBlock failureBlock = ^(NSError *error) {
    NSLog(@"Error listing files: %@", error);
};

Thanks, 
Chinna

**Comment by dleehr** [comment]
Not sure exactly - I haven't done much with Swift. I'd suggest looking at something like this: http://www.learnswift.io/blog/2014/6/9/writing-completion-blocks-with-closures-in-swift or Apple's  documentation on interoperability between Swift and Objective-C (e.g. https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html)

**Comment by chinnasamymca** [comment]
Hi, 
   I have tested your code with Objective-C project, The app is crashing and show a error.
Thanks, Chinna 


     On Friday, 26 June 2015 12:05 AM, Dan Leehr <notifications@github.com> wrote:
   

 Not sure exactly - I haven't done much with Swift. I'd suggest looking at something like this: http://www.learnswift.io/blog/2014/6/9/writing-completion-blocks-with-closures-in-swift or Apple's documentation on interoperability between Swift and Objective-C (e.g. https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html)—
