### ISSUE TITLE
How to use this library for mac app. Using swift

### ISSUE THREAD

**Issue by sadiqshaikh** [dleehr/DLSFTPClient#23]
Hi Dan,

I want to use one of your library in my mac project. DLSFTPClient to connect to sftp server & file transfer. it works in your iOS demo but not working for the mac demo i prepared. It sometimes connects & sometimes crashes giving following error

[__NSArrayM count]: message sent to deallocated instance 0x11824dfd0
(lldb)

at first line if (index >= [addresses count])` in following code in DLSFTPConnection.m

- (void)connectToAddressAtIndex:(NSUInteger)index inArray:(NSArray *)addresses {
    if (index >= [addresses count]) {
        [self _disconnect];
        [self failConnectionWithErrorCode:eSFTPClientErrorUnableToConnect
                         errorDescription:@"Unable to connect"];
        self.connectionSuccessBlock = nil;
        return;
    }

Can you please suggest some way to find solution to this problem?

Thanks,

Sadiq

**Comment by sadiqshaikh** [comment]
following is the attachment i'm working on
[SFTP-DLS-Demo.zip](https://github.com/dleehr/DLSFTPClient/files/165451/SFTP-DLS-Demo.zip)

**Comment by sadiqshaikh** [comment]
The error occurs randomly - only sometimes it goes in success otherwise it always crashes

**Comment by dleehr** [comment]
Do you have a stacktrace for that? I see that addresses is bridged from `CFHostGetAddressing`, so I think ARC would keep it alive and copy it in the blocks, but i'm not sure what's calling connectToAddressAtIndex in your case.

**Comment by sadiqshaikh** [comment]
have you checked the demo i have sent. i'm just calling the method in swift code

**Comment by sadiqshaikh** [comment]
This is working now - Converted the code to Non - ARC, 
Thanks Dleehr
