### ISSUE TITLE
Is This Library multithreaded

### ISSUE THREAD

**Issue by sadiqshaikh** [dleehr/DLSFTPClient#24]
Hi Dan,

Can we upload multiple files at at time? Also can multiple simultaneous requests possible - like upload with delete, rename, get directory etc

Thanks,
-Mohammad Sadiq

**Comment by sadiqshaikh** [comment]
Yes it is possible, by creating multiple connections. Thanks

**Comment by dleehr** [comment]
Yeah that's what I do - I use one connection for listing files and another for transfers.
